name: shared_domain
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  bloc: ^8.1.1
  collection: ^1.17.0
  decimal: ^2.3.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.0.3
  get_it: ^7.2.0
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.0.0
  rxdart: ^0.27.1
  synchronized: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.0.3+1
  json_serializable: ^6.0.0
  mocktail: ^0.3.0
  test: ^1.23.1 
  very_good_analysis: ^5.0.0+1
