include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - build/**
    - lib/**.g.dart
    - lib/**.freezed.dart

linter:
  rules:
    public_member_api_docs: false
    require_trailing_commas: false
    # file_names: false
    # no_default_cases: false
