name: middelkamp_dev_app
description: Example Flutter app architecture for enterprise projects

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  decimal: ^2.3.2
  feature_auth_data:
    path: packages/features/auth/auth_data
  feature_auth_domain:
    path: packages/features/auth/auth_domain
  feature_auth_presentation:
    path: packages/features/auth/auth_presentation
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  go_router: ^9.0.3
  shared_data:
    path: packages/shared/shared_data
  shared_domain:
    path: packages/shared/shared_domain
  shared_presentation:
    path: packages/shared/shared_presentation

dev_dependencies:
  flutter_test:
    sdk: flutter
  melos: ^3.0.0
  very_good_analysis: ^5.0.0+1

flutter:
  uses-material-design: true
