name: flutter_architecture_api_project_dart_frog
description: A Dart Frog server for the Project microservice
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.0
  dart_jsonwebtoken: ^3.2.0
  flutter_architecture_api_project_application:
    path: ../../packages/project/application
  flutter_architecture_api_project_domain:
    path: ../../packages/project/domain
  flutter_architecture_api_project_infrastructure:
    path: ../../packages/project/infrastructure
  flutter_architecture_api_project_presentation_dart_frog:
    path: ../../packages/project/presentation_dart_frog
  flutter_architecture_api_shared_application:
    path: ../../packages/shared/application
  flutter_architecture_api_shared_infrastructure:
    path: ../../packages/shared/infrastructure
  flutter_architecture_api_shared_presentation_dart_frog:
    path: ../../packages/shared/presentation_dart_frog

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: ^6.0.0