name: shared_presentation
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  collection: ^1.17.0
  decimal: ^2.3.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.0.3
  hydrated_bloc: ^9.1.0
  json_annotation: ^4.0.0
  shared_domain:
    path: ../shared_domain

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.0.0
  very_good_analysis: ^5.0.0+1
