name: flutter_architecture_api_shared_infrastructure
description: Shared infrastructure layer for the Flutter Architecture API
version: 0.1.0
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dart_frog: ^1.2.0
  dart_jsonwebtoken: ^3.2.0
  flutter_architecture_api_shared_application:
    path: ../application
  flutter_architecture_api_shared_domain:
    path: ../domain
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: ^6.0.0