name: flutter_architecture_api_project_infrastructure
description: Project infrastructure layer for the Flutter Architecture API
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  dart_jsonwebtoken: ^3.2.0
  flutter_architecture_api_project_application:
    path: ../application
  flutter_architecture_api_project_domain:
    path: ../domain
  flutter_architecture_api_shared_application:
    path: ../../shared/application
  flutter_architecture_api_shared_domain:
    path: ../../shared/domain

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.5
  very_good_analysis: ^6.0.0